# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /run/media/neo/ssd_storage/ue5
GAMEPROJECTFILE =/run/media/neo/ssdWorkspaceUE/Unreal Projects/thirdPersoneShooter/thirdPersoneShooter.uproject

TARGETS = \
	thirdPersoneShooter-Linux-DebugGame  \
	thirdPersoneShooter-Linux-Shipping  \
	thirdPersoneShooter \
	thirdPersoneShooterEditor-Linux-DebugGame  \
	thirdPersoneShooterEditor-Linux-Shipping  \
	thirdPersoneShooterEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/RunMono.sh" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool.exe"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend UnrealEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug UnrealEditor-Linux-Debug


thirdPersoneShooter-Linux-DebugGame:
	 $(PROJECTBUILD) thirdPersoneShooter Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

thirdPersoneShooter-Linux-Shipping:
	 $(PROJECTBUILD) thirdPersoneShooter Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

thirdPersoneShooter:
	 $(PROJECTBUILD) thirdPersoneShooter Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

thirdPersoneShooterEditor-Linux-DebugGame:
	 $(PROJECTBUILD) thirdPersoneShooterEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

thirdPersoneShooterEditor-Linux-Shipping:
	 $(PROJECTBUILD) thirdPersoneShooterEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

thirdPersoneShooterEditor:
	 $(PROJECTBUILD) thirdPersoneShooterEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
